version: '3.6'
services:
  db:
    container_name: ssuspot_sns_database
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: testpassword1
      POSTGRES_USER: ssuspot
      POSTGRES_DB: ssuspot_sns
      TZ: "Asia/Seoul"
    volumes:
      - ./postgres/initdb:/docker-entrypoint-initdb.d
    tty: true
    ports:
      - "5434:5432"

  redis:
    container_name: ssuspot_sns_redis
    image: redis:latest
    ports:
      - "6379:6379"
