version: '3.6'
services:
  db:
    container_name: ssuspot_sns_database
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: testpassword1
      POSTGRES_USER: ssuspot
      POSTGRES_DB: ssuspot_sns
      TZ: "Asia/Seoul"
    volumes:
      - ./postgres/initdb:/docker-entrypoint-initdb.d
    tty: true
    ports:
      - "5434:5432"

  redis:
    container_name: ssuspot_sns_redis
    image: redis:latest
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "qualifiedOption565"
    ports:
      - "6379:6379"

  zookeeper:
    container_name: ssuspot_sns_zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    container_name: ssuspot_sns_kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "likes-topic:1:1,processed-likes-topic:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
