version: '3.6'
services:
  db:
    container_name: ssuspot_sns_db
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: ${SSUSPOT_SNS_DB_PASSWORD}
      POSTGRES_USER: ${SSUSPOT_SNS_DB_USERNAME}
      POSTGRES_DB: ssuspot_sns
      TZ: "Asia/Seoul"
    volumes:
      - ./postgres/initdb:/docker-entrypoint-initdb.d
    tty: true
    ports:
      - "5434:5432"