spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SSUSPOT_SNS_DB_URL}
    username: ${SSUSPOT_SNS_DB_USERNAME}
    password: ${SSUSPOT_SNS_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
  servlet:
    multipart:
    enabled: true
    max-file-size: 10MB # 한개 파일의 최대 사이즈 (default: 1MB)
    max-request-size: 10MB # 한개 요청의 최대 사이즈 (default: 10MB)
  redis:
    host: ${SSUSPOT_REDIS_HOST}
    port: ${SSUSPOT_REDIS_PORT}

app:
  jwt:
    secret: ${SSUSPOT_JWT_SECRET}
    accessTokenExpirationMS: 86400000
    refreshTokenExpirationMS: 2592000000
cloud:
  aws:
    s3:
      bucket: ${SSUSPOT_S3_BUCKET_NAME}
    credentials:
      access-key: ${SSUSPOT_S3_ACCESS_KEY}
      secret-key: ${SSUSPOT_S3_SECRET_KEY}
    region:
      static: ${SSUSPOT_S3_REGION}
    stack:
      auto: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
