spring:
  profiles:
    active: prod
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 25
          batch_versioned_data: true
        order_inserts: true
        order_updates: true

logging:
  level:
    root: WARN
    com.ssuspot.sns: INFO
    org.springframework.security: WARN

# 프로덕션 환경 보안 설정
server:
  error:
    include-message: never
    include-stacktrace: never
    include-exception: false

# 프로덕션 환경 토큰 만료 시간
app:
  jwt:
    accessTokenExpirationMS: 86400000    # 24시간
    refreshTokenExpirationMS: 2592000000 # 30일

# 프로덕션 환경 CORS 설정은 환경 변수로 관리
cors:
  allowed-origins: ${SSUSPOT_CORS_ALLOWED_ORIGINS:https://app.ssuspot.com}