spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/ssuspot_dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    com.ssuspot.sns: debug

# 개발 환경에서는 더 짧은 토큰 만료 시간 사용
app:
  jwt:
    accessTokenExpirationMS: 3600000  # 1시간
    refreshTokenExpirationMS: 86400000 # 24시간