spring:
  profiles:
    active: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  redis:
    host: localhost
    port: 6379
    password: ""

# 테스트용 고정 시크릿 키 (실제 환경에서는 절대 사용하지 말 것)
app:
  jwt:
    secret: test-secret-key-for-jwt-token-generation-must-be-at-least-32-characters-long
    accessTokenExpirationMS: 3600000   # 1시간
    refreshTokenExpirationMS: 86400000 # 24시간

# 테스트 환경 S3 설정 (LocalStack 등 사용 시)
cloud:
  aws:
    s3:
      bucket: test-bucket
    credentials:
      access-key: test-access-key
      secret-key: test-secret-key
    region:
      static: us-east-1