spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/ssuspot_sns
    username: ${SSUSPOT_SNS_DB_USERNAME}
    password: ${SSUSPOT_SNS_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

app:
  jwt:
    secret: ${SSUSPOT_JWT_SECRET}
    accessTokenExpirationMS: 86400000
    refreshTokenExpirationMS: 2592000000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
