spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SSUSPOT_SNS_DB_URL}
    username: ${SSUSPOT_SNS_DB_USERNAME}
    password: ${SSUSPOT_SNS_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

app:
  jwt:
    secret: ${SSUSPOT_JWT_SECRET}
    accessTokenExpirationMS: 86400000
    refreshTokenExpirationMS: 2592000000
  bucket:
    accessKey: ${SSUSPOT_S3_ACCESS_KEY}
    secretKey: ${SSUSPOT_S3_SECRET_KEY}
    region: ${SSUSPOT_S3_REGION}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
